<a href="https://colab.research.google.com/github/Adr1an12/projeto-knn-emprestimo/blob/main/KNN_emprestimos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    classification_report
)

In [2]:
from google.colab import files
import pandas as pd

# Fazer upload do arquivo CSV
uploaded = files.upload()

df = pd.read_csv("dataset_emprestimo_aprovacao.csv")

df.head()

Saving dataset_emprestimo_aprovacao.csv to dataset_emprestimo_aprovacao.csv

   renda_mensal  score_credito  dividas_ativas  emprestimo_aprovado
0       5493.43            480               4                    0
1       4223.47            600               5                    0
2       5795.38            609               5                    1
3       7546.06            554               1                    1
4       4031.69            631               0                    1

In [3]:
print("Informações gerais:")
df.info()

Informações gerais:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   renda_mensal         100 non-null    float64
 1   score_credito        100 non-null    int64
 2   dividas_ativas       100 non-null    int64
 3   emprestimo_aprovado  100 non-null    int64
dtypes: float64(1), int64(3)
memory usage: 3.3 KB

In [4]:
df.describe()

       renda_mensal  score_credito  dividas_ativas  emprestimo_aprovado
count    100.000000     100.000000      100.000000            100.00000
mean    4596.775500     651.220000        1.990000              0.79000
std     2623.031756     109.977921        1.690705              0.40936
min     1200.000000     420.000000        0.000000              0.00000
25%     3274.882500     553.500000        1.000000              1.00000
50%     4312.340000     660.000000        2.000000              1.00000
75%     5541.177500     725.500000        3.000000              1.00000
max    19546.000000     900.000000        8.000000              1.00000

In [5]:
df.isnull().sum()

renda_mensal           0
score_credito          0
dividas_ativas         0
emprestimo_aprovado    0
dtype: int64

In [6]:
X = df[['renda_mensal', 'score_credito', 'dividas_ativas']]

y = df['emprestimo_aprovado']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Dados divididos com sucesso.")

Dados divididos com sucesso.

In [8]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Dados normalizados.")

Dados normalizados.

In [9]:
modelo = KNeighborsClassifier(n_neighbors=5)

modelo.fit(X_train, y_train)

print("Modelo treinado.")

Modelo treinado.

In [10]:
y_pred = modelo.predict(X_test)

print(y_pred)

[1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

In [11]:
matriz = confusion_matrix(y_test, y_pred)

print("Matriz de Confusão:")
print(matriz)

Matriz de Confusão:
[[ 0  3]
 [ 1 16]]

In [12]:
acuracia = accuracy_score(y_test, y_pred)

print("Acurácia:", acuracia)

Acurácia: 0.8

In [13]:
precisao = precision_score(y_test, y_pred)

print("Precisão:", precisao)

Precisão: 0.8421052631578947

In [14]:
recall = recall_score(y_test, y_pred)

print("Recall:", recall)

Recall: 0.9411764705882353

In [15]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.84      0.94      0.89        17

    accuracy                           0.80        20
   macro avg       0.42      0.47      0.44        20
weighted avg       0.72      0.80      0.76        20

In [16]:
novo_cliente = np.array([[5000, 650, 2]])

novo_cliente = scaler.transform(novo_cliente)

previsao = modelo.predict(novo_cliente)

if previsao[0] == 1:
    print("Empréstimo APROVADO")
else:
    print("Empréstimo NÃO APROVADO")

Empréstimo APROVADO

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [17]:
print("O modelo KNN foi treinado e avaliado com sucesso.")

O modelo KNN foi treinado e avaliado com sucesso.